# !! IMPORTANT !!
#
# This file uses the YAML format as described in the documentation:
#   http://docs.mongodb.org/manual/reference/configuration-options/

storage:
    dbPath: "/data/db"
    #engine: wiredTiger

systemLog:
    destination: file
    path: "mongodb.log"
    quiet: true
    logAppend: true

net:
    port: 27017
    bindIp: 127.0.0.1,cluster0.o6gggpj.mongodb.net
    #ssl:
    #    mode: disabled
    #
   
#net:
#  tls:
#    clusterAuthX509:
#      attributes: DC=MongoDB

security:
    authorization: enabled
    keyFile: key1
    #clusterIpSourceAllowlist:
    #clusterAuthMode:

replication:
    replSetName: rs0

setParameter:
   enableLocalhostAuthBypass: false
   httpVerboseLogging: true
   # enableDetailedConnectionHealthMetricLogLines: true
   logLevel: 2
   diagnosticDataCollectionDirectoryPath: mongos.diagnostic.data
   # progressMonitor: { interval: 1000, deadline: 300 }
   # tcpFastOpenClient: true
   # pessimisticConnectivityCheckForAcceptedConnections: true
    #redactEncryptedFields:
    #linux

# Specifies one of the MongoDB parameters described here:
#   http://docs.mongodb.org/manual/reference/parameters/
#
# You can specify multiple setParameter fields such as:
#   setParameter: {enableTestCommands: 1}
#setParameter:
