use journal

db.contentCollection.insertMany([{ isActive: true, title: "Stutter in Time", date: "060101", category: "poems", content: `<div style="text-align:center;"> <h4>Stutter in Time - 2006</h4> (A pantoum)</br></br>At the end of time</br>I saw a room</br></br>It was a dark, desolate hallway, with an old man by six pillars of light</br>I stepped into one, and, at the end of the path,</br>I saw a room</br>that saw my life pass by its eyes—bed, a mirror—and among its welcoming walls</br></br>I stepped into one, and, at the end of the path,</br>I saw all the things I had ever seen and all the people I ever knew</br>that saw my life pass by their eyes—mind, a heart—and, through their weary walls</br>I sensed a trace of my soul I had left long ago, in another time</br>where all the things I had ever seen and all the people I ever knew</br>were still with me. In this world beyond the wall in my room</br>I sensed a trace of my soul that I had left long ago</br>where many friends and lovers alike</br>were still with me, in this world within my room.</br></br>Here, Time could not touch us.</br></br>My many friends and lovers alike</br>gathered around me, like a mighty meeting of memories</br>that Time could not touch.</br>I saw all the replays and rewinds</br>gather around me like a mighty  meeting of memories</br>where me and my love sang timeless songs only our mothers would know</br>who surely constantly replayed and rewound them.</br>We were sure</br>our parents and their loves sang these same timeless songs only their mothers would know</br>in another time,</br>and we were sure</br>we would live forever.</br></br>However, in another time</br>I saw a world without time.</br>We would live forever</br>if only in a void.</br></br>But, in this world without time</br>I still saw a room</br>if only in a void</br>So, I will look for us</br>in this room I saw</br>inside the dark, desolate hallway, with an old man by six pillars of light</br>and I will look for us</br>until the end of time </div>` },

{ isActive: true, title: "Dead and Alive", date: "050101", category: "poems", content: `<div style="text-align:center;"> <h4>Dead and Alive - 2005</h4>  A book broke my heart one day</br></br>I walked down</br>A deserted hallway in my high school—it was after school.</br>And soon, by the main entrance, I saw the Prayer Book</br>Sitting majestically on the podium, in front of the main entrance.</br></br>Boredom beckoned me toward it and I answered.</br>I perused the  prayers for awhile until I came across this one person.</br>This person  prayed for someone sent to war.</br>And to the side of the description sat a column that asked</br>If the person being prayed for was dead or alive</br></br>It said “Both.” </div>` },

{ isActive: true, title: "ICE", date: "170101", category: "poems", content: `<div style="text-align:center;"> <h4>ICE - 2017</h4> ICE falls all over the land</br>sprinkled by a childish man</br>freezing people</br>while the forests burn</br>and the world turns without us</br></br>They hope the ICE will whiten everything</br>covering all the brown dirt and stopping time</br>while somehow not freezing their hearts cold</br>and hoping the truth goes untold</br></br>But anyone who knows ICE knows it numbs you</br>so  that when the end comes</br>it feels like a sweet sleep</br>instead of dark death</br></br>And unless we return to warmth</br>the burning forests will melt the ice</br>and drown us all </div>` },

{ isActive: true, title: "100 Years of Solitary", date: "180102", category: "poems", content: `<div style="text-align:center;"> <h4>100 Years of Solitary - 2018</h4> 100 years of solitary</br>would be very rough</br>but there are those so cold inside</br>they'd ask if that's enough</br></br>Comics and comedy</br>come to reality</br>with Fortresses of Solitude</br>peppered from sea to shining sea</br>in the   land of the free</br></br>Those banished gaze into the abyss every day</ br>while we gaze away</br>and it becomes them</br>while we become numb</br>and deaf and dumb to their humanity</br></br>Just like the comics</br>one day, the banished will break free</br>and the abyss will gaze back at all of us</br>and we'll have to taste the tears and gas</br>and  eat the loaves</br>and freeze and fry to death in tattered clothes</br>exposed naked in judgment before the gods</br>and answer how we all   got here </div>` },

{ isActive: true, title: "Beautiful Black Hole", date: "070101", category: "poems", content: `<div style="text-align:center;"> <h4> Beautiful Black Hole - 2007 </h4> An ineffable beauty</br>Belies the lovely lies</br>Inside her eyes</br></br>So gleamingly green</br>With all</br>The venemous envy</br>Of all</br>The women in</br>The world</br></br>Past present and future</br>Like a mighty</br>Amalgamation</br>Of all states</br>And all nations</br>And all skies</br>And all stars</br>And all alls</br></br>She is beautiful</br>Even in her worst</ br>Because even that gleaming, glowing green is just an</br>Illusion</br>So at any given</br>Moment</br>Of any given point in</br>Time</br>I can always know her</br>But never know her at all</br></br>And it’s a beautiful paradox</br>That forever jumbles my mind</br>And distresses me</br>And perplexes me</br>Yet pulls me</br>Like a black hole in the</  br>Vast mass of</br>Outer Space</br></br>Nothing can escape</br>But perhaps that's good</br></br>I'm not sure I'd want to </div>` }
])


db.contentCollection.insertOne({isActive: true, category: "homes", title: "Poems section updated", date: "250831", content: `<div> I have updated the <a href="poems">poems</a> section; the old slideshow has been replaced with individual text pages for the poems. I have also changed the selection of poems.</div>`})

newPoemsViewPL = [ { '$match': { category: 'poems', isActive: true, title: { '$ne': null } } }, { '$set': { baseCase: { '$toLower': { '$replaceAll': { input: '$title', find: ' ', replacement: '-' } } } } }, { '$set': { realPath: { '$concat': ['poems', '/', '$baseCase'] } } }, { '$unset': ['_id', 'category', 'isActive'] }]

db.createView("poems", "contentCollection", newPoemsViewPL);
